# Generated by Django 4.0.5 on 2022-06-12 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_part_car_car_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car',
            new_name='part',
        ),
    ]
